# Generated by Django 5.0.6 on 2024-06-25 08:48

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.CharField(default='+996', max_length=14)),
                ('age', models.IntegerField(default=18)),
                ('gender', models.TextField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100)),
                ('status_of_reader', models.TextField(choices=[('beginner', 'beginner'), ('not_readers', 'not_readers'), ('amateur', 'amateur'), ('veteran', 'veteran')], max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('literary_club', models.CharField(default='Клуб не определен', max_length=100)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
