# Generated by Django 5.0.6 on 2024-06-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="library",
            name="tags",
            field=models.ManyToManyField(to="books.tag"),
        ),
    ]
